---
- name: Clone ODIN from GitHub
  become: true
  git:
    repo: https://github.com/chrismaddalena/ODIN.git
    dest: "{{ odin_git_location }}/ODIN"
    update: yes
  register: odin

# Currently broken in Travis: https://github.com/pypa/pipenv/issues/2078
- name: Install Python requirements
  become: true
  become_flags: -E
  when: odin.changed
  shell: pipenv install
  environment:
    PATH: "$HOME/.local/bin:{{ ansible_env.PATH }}"
  args:
    chdir: "{{ odin_git_location }}/ODIN"

 - name: Grab chromedriver
   become: true
   when: odin.changed
   unzip:
     remote_src: yes
     src: https://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip
     dest: "{{ odin_git_location }}/chromedriver"

- name: Install sqlite3
  become: true
  when: ansible_os_family == "Debian" and odin.changed
  apt:
    name: sqlite3
    update_cache: yes
    state: latest

- name: Install awscli
  become: true
  when: ansible_os_family == "Debian" and odin.changed
  apt:
    name: awscli
    update_cache: yes
    state: latest

- name: Install ODIN
  when: odin.changed
  become: true
  become_flags: -E
  command: pipenv install
  args:
    chdir: "{{ odin_git_location }}/ODIN"
